# Generated by Django 5.1 on 2024-10-12 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=30)),
                ('situacao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATIVA', 'Ativa'), ('EXCLUIDA', 'Excluida')], default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=14)),
                ('logradouro', models.CharField(max_length=100)),
                ('nres', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('dtnasc', models.DateField(blank=True, null=True)),
                ('dtcadastro', models.DateField(blank=True, null=True)),
                ('processo', models.CharField(max_length=30)),
                ('observacoes', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='solicitantes.situacao')),
            ],
        ),
    ]
