# Generated by Django 5.1 on 2024-08-19 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivelocorrencia', models.IntegerField()),
                ('datahora', models.DateField(blank=True, null=True)),
                ('latocorr', models.FloatField()),
                ('longocorr', models.FloatField()),
                ('status', models.IntegerField()),
                ('link', models.CharField(max_length=255)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitante', to='solicitantes.solicitante')),
            ],
        ),
    ]
