# Generated by Django 5.1 on 2024-10-12 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitantes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivelocorrencia', models.IntegerField()),
                ('datahora', models.DateField(blank=True, null=True)),
                ('latocorr', models.FloatField()),
                ('longocorr', models.FloatField()),
                ('status', models.IntegerField()),
                ('opcao_ocorrencia', models.CharField(choices=[('ATENDIDA', 'Atendida'), ('EM ATENDIMENTO', 'Em atendimento'), ('CONCLUIDA', 'Concluida'), ('EM AVALIACAO', 'Em avaliacao')], default='', max_length=100)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitante', to='solicitantes.solicitante')),
            ],
        ),
    ]
